const root=document.documentElement;const menuButton=document.querySelector('.menu-toggle');const nav=document.querySelector('.nav-links');const themeButton=document.getElementById('themeToggle');const topButton=document.getElementById('scrollTop');

menuButton?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open));});
document.querySelectorAll('.nav-links a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');menuButton?.setAttribute('aria-expanded','false');}));

const savedTheme=localStorage.getItem('theme');if(savedTheme)root.dataset.theme=savedTheme;themeButton?.addEventListener('click',()=>{const next=root.dataset.theme==='dark'?'light':'dark';root.dataset.theme=next;localStorage.setItem('theme',next);});
topButton?.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));

const navLinks=[...document.querySelectorAll('.nav-links a')];const sections=navLinks.map(link=>document.querySelector(link.hash)).filter(Boolean);const setActive=id=>navLinks.forEach(link=>link.classList.toggle('active',link.hash===`#${id}`));
if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{const active=entries.filter(entry=>entry.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(active)setActive(active.target.id);},{rootMargin:'-25% 0px -60% 0px',threshold:[.05,.3,.6]});sections.forEach(section=>observer.observe(section));}

const stickers=['observing & organizing','field notes first','making room for context','archive in progress'];const stickerButton=document.getElementById('stickerButton');const stickerDisplay=document.getElementById('stickerDisplay');stickerButton?.addEventListener('click',()=>{const next=stickers[(stickers.indexOf(stickerButton.textContent)+1)%stickers.length];stickerButton.textContent=next;if(stickerDisplay)stickerDisplay.textContent=next;});

document.querySelectorAll('.gallery-shell').forEach(shell=>{const track=shell.querySelector('.gallery-track');if(!track)return;const real=[...track.querySelectorAll('.gallery-image')];const visible=shell.classList.contains('practice-gallery')?1:3;if(real.length>visible){const clone=slide=>{const copy=slide.cloneNode(true);copy.dataset.clone='true';copy.tabIndex=-1;return copy;};track.prepend(...real.slice(-visible).map(clone));track.append(...real.slice(0,visible).map(clone));const first=real[0],last=real.at(-1);let timer,correcting=false;const jump=left=>{correcting=true;track.scrollTo({left,behavior:'auto'});requestAnimationFrame(()=>correcting=false);};requestAnimationFrame(()=>jump(first.offsetLeft));const correct=()=>{if(correcting)return;const start=first.offsetLeft,end=last.offsetLeft+last.offsetWidth;if(track.scrollLeft<=start-4)jump(end-track.clientWidth);else if(track.scrollLeft>=end-4)jump(start);};track.addEventListener('scroll',()=>{clearTimeout(timer);timer=setTimeout(correct,90)},{passive:true});track.addEventListener('scrollend',correct);}
const move=direction=>{const slide=track.querySelector('.gallery-image');const gap=parseFloat(getComputedStyle(track).gap)||0;track.scrollBy({left:direction*(slide.offsetWidth+gap),behavior:'smooth'});};shell.querySelector('.prev')?.addEventListener('click',()=>move(-1));shell.querySelector('.next')?.addEventListener('click',()=>move(1));});

const modal=document.getElementById('lightboxModal');const modalImage=document.getElementById('lightboxImage');const closeModal=()=>{modal?.classList.remove('is-open');modal?.setAttribute('aria-hidden','true');document.body.style.overflow='';};document.addEventListener('click',event=>{const galleryButton=event.target.closest('.gallery-image');if(galleryButton){const image=galleryButton.querySelector('img');if(image&&modal&&modalImage){modalImage.src=galleryButton.dataset.full||image.currentSrc||image.src;modalImage.alt=image.alt;modal.classList.add('is-open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}return;}if(event.target===modal?.querySelector('.lightbox-backdrop')||event.target.id==='lightboxClose')closeModal();});document.addEventListener('keydown',event=>{if(event.key==='Escape')closeModal();});
